name       : anoise-gui
version    : 0.0.4
release    : 1
source     :
    - https://launchpad.net/anoise/0.0.x/0.0.x/+download/anoise-gui_0.0.4.tar.gz : b97553fe661c55d3563dc8031834b51a36387ca3eb856eb78c046e4d8efc868b
license    : GPL-3.0
component  : multimedia.audio
summary    : GUI for ANoise
description: GUI for ANoise
builddeps  :
    - python-distutils-extra
rundeps    :
    - anoise
build      : |
    %python_setup
install    : |
    %python_install
